spring:
  application:
    name: CatFactsWebApp

server:
  port: ${PORT:8080}
  error:
      include-stacktrace: never

randomuser:
  api:
    url: https://randomuser.me/api/

catfact:
  api:
    url: https://cat-fact.herokuapp.com/facts/random

REMOTE_ALLOWED_ORIGIN: https://gray-smoke-0178eac03.5.azurestaticapps.net
LOCAL_ALLOWED_ORIGIN: http://localhost:5173